package Panel;

import Class.Database;
import Class.JPanelLoader;
import UI.LoginUI;
import UI.MainUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class loginPanel extends javax.swing.JPanel {

    JPanelLoader panelLoad = new JPanelLoader();
    Connection connect;
    MainUI main;
    LoginUI login;
    static int user;
    public static String name;
    public static String path;

    public loginPanel(LoginUI login) {
        initComponents();
        lbl_checkUsername.setVisible(false);
        lbl_checkPassword.setVisible(false);
        main = new MainUI();
        this.login = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        lbl_forgotPassword = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        img_close = new javax.swing.JLabel();
        lbl_checkUsername = new javax.swing.JLabel();
        lbl_checkPassword = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txt_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_usernameMouseClicked(evt);
            }
        });

        lbl_username.setText("Username");

        lbl_password.setText("Password");

        txt_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passwordMouseClicked(evt);
            }
        });

        lbl_forgotPassword.setText("Forgot Password");
        lbl_forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotPasswordMouseClicked(evt);
            }
        });

        btn_login.setText("Login");
        btn_login.setPreferredSize(new java.awt.Dimension(70, 27));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel1.setText("Login");

        img_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/close_window_30px.png"))); // NOI18N
        img_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                img_closeMouseClicked(evt);
            }
        });

        lbl_checkUsername.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbl_checkUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbl_checkUsername.setText("Username Incorrect");

        lbl_checkPassword.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbl_checkPassword.setForeground(new java.awt.Color(255, 0, 0));
        lbl_checkPassword.setText("Password Incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(img_close, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_username)
                                .addComponent(lbl_password)
                                .addComponent(txt_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_checkUsername, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lbl_checkPassword)
                            .addComponent(lbl_forgotPassword))
                        .addGap(30, 30, 30))))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(img_close)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_username)
                .addGap(3, 3, 3)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbl_checkUsername)
                .addGap(15, 15, 15)
                .addComponent(lbl_password)
                .addGap(3, 3, 3)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(lbl_checkPassword)
                .addGap(0, 0, 0)
                .addComponent(lbl_forgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String lastUsername = null;
        connect = Database.openConnection();
        
        try {
            String sql1 = "SELECT userID, firstName, lastName, gender, role FROM user WHERE username = ? AND password = ?";
            PreparedStatement statement = connect.prepareStatement(sql1);
            statement.setString(1, txt_username.getText());
            statement.setString(2, txt_password.getText());
            ResultSet result1 = statement.executeQuery();
            if (result1.next()) {
                user = result1.getInt("userID");
                String gender = result1.getString("gender");
                String role = result1.getString("role");
                name = result1.getString("firstName") + " " + result1.getString("lastName");

                if (gender.equals("MALE")) {
                    path = "D:\\COT\\COTFinalProject\\Service-Management-System\\Desktop\\src\\Icons\\male_49px.png";
                } else if (gender.equals("FEMALE")) {
                    path = "D:\\COT\\COTFinalProject\\Service-Management-System\\Desktop\\src\\Icons\\female_49px.png";
                }

                switch (role) {
                    case "ADMIN" ->
                        main.adminLoad();
                    case "CASHIER" ->
                        main.cashierLoad();
                    case "MECHANIC" ->
                        main.technicianLoad();
                }

                login.dispose();
                main.setVisible(true);

            } else {
                String sql2 = "SELECT username FROM user";
                PreparedStatement statement2 = connect.prepareStatement(sql2);
                ResultSet result2 = statement2.executeQuery();

                while (result2.next()) {
                    String username = result2.getString("username");
                    
                    if (username.equals(txt_username.getText())) {
                        lbl_checkUsername.setVisible(false);
                        lastUsername = username;
                        break;
                    } else {
                        lbl_checkUsername.setVisible(true);
                    }
                }
                
                String sql3 = "SELECT password FROM user WHERE username = '" + lastUsername + "'";
                PreparedStatement statement3 = connect.prepareStatement(sql3);
                ResultSet result3 = statement3.executeQuery();

                while (result3.next()) {
                    String password = result3.getString("password");

                    if (password.equals(txt_password.getText())) {
                        lbl_checkPassword.setVisible(false);
                        break;
                    } else {
                        lbl_checkPassword.setVisible(true);
                    }
                }
            }
            connect.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void lbl_forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotPasswordMouseClicked
        forgotPasswordPanel forgot = new forgotPasswordPanel(login);
        panelLoad.jPanelLoader(this, forgot);
    }//GEN-LAST:event_lbl_forgotPasswordMouseClicked

    private void img_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_img_closeMouseClicked

    private void txt_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_usernameMouseClicked
        if (lbl_checkUsername.isVisible()) {
            txt_username.setText("");
            lbl_checkUsername.setVisible(false);
            lbl_checkPassword.setVisible(false);
        }
    }//GEN-LAST:event_txt_usernameMouseClicked

    private void txt_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passwordMouseClicked
        if (lbl_checkPassword.isVisible()) {
            txt_password.setText("");
            lbl_checkPassword.setVisible(false);
        }
    }//GEN-LAST:event_txt_passwordMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel img_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_checkPassword;
    private javax.swing.JLabel lbl_checkUsername;
    private javax.swing.JLabel lbl_forgotPassword;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
