package Panel;

import Class.Database;
import Notification.Notification;
import static Notification.Notification.Type.SUCCESS;
import static Notification.Notification.Type.WARNING;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

public class servicePanel extends javax.swing.JPanel {

    Connection connect;
    DecimalFormat decimalFormat = new DecimalFormat("0.00");

    public servicePanel() {
        initComponents();

        // TABLE CELL RENDERING
        DefaultTableCellRenderer rightAlign = new DefaultTableCellRenderer();
        rightAlign.setHorizontalAlignment(SwingConstants.RIGHT);
        tbl_service.getColumnModel().getColumn(2).setCellRenderer(rightAlign);
        tbl_service.getColumnModel().getColumn(3).setCellRenderer(rightAlign);
        tbl_service.getColumnModel().getColumn(4).setCellRenderer(rightAlign);
        //====================================================================//

        loadData();
    }

    private void loadData() {
        try {
            connect = Database.openConnection();
            String sql = "SELECT * FROM service";
            PreparedStatement statement = connect.prepareStatement(sql);

            ResultSet result = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbl_service.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String id = result.getString("serviceID");
                String name = result.getString("name");
                String price = decimalFormat.format(result.getDouble("price"));
                String discount = decimalFormat.format(result.getDouble("discount"));
                String subPrice = decimalFormat.format(result.getDouble("subPrice"));

                model.addRow(new Object[]{id, name, price, discount, subPrice});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e + "Data Load Unsuccessful", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearData() {
        txt_id.setText("");
        txt_name.setText("");
        txt_price.setText("");
        txt_discount.setText("");
        search.setText("");
    }

    private void enableButton() {
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_add.setEnabled(false);
    }

    private void disableButton() {
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_add.setEnabled(true);
    }

    private void showNotification(String message, Notification.Type type) {
        new Notification(this, type, Notification.Location.TOP_CENTER, message).showNotification();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lbl_userDetails = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_price = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        lbl_discount = new javax.swing.JLabel();
        txt_discount = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        lbl_search = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_service = new javax.swing.JTable();

        setBackground(new java.awt.Color(211, 211, 211));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lbl_userDetails.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_userDetails.setText("Service Details");

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_30px.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eraser_30px.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        lbl_id.setText("Service ID");

        txt_id.setEnabled(false);

        lbl_name.setText("Service Name");

        lbl_price.setText("Price");

        lbl_discount.setText("Discount");

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update_30px.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setEnabled(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel_30px.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lbl_userDetails)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(88, 88, 88)
                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(lbl_discount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(67, 67, 67)
                                .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_userDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_id)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_price)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_discount)
                    .addComponent(txt_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_update)
                    .addComponent(btn_delete))
                .addContainerGap())
        );

        lbl_search.setText("Search by Service Name");

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        tbl_service.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_service.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service ID", "Service Name", "Price", "Discount", "Sub Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_service.setRowHeight(30);
        tbl_service.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_serviceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_service);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_search)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            connect = Database.openConnection();
            String sql = "INSERT INTO service(name, price, discount, subPrice) VALUES(?, ?, ?, ?)";
            PreparedStatement statement = connect.prepareStatement(sql);
            statement.setString(1, txt_name.getText().toUpperCase());
            statement.setDouble(2, Double.parseDouble(txt_price.getText()));
            if (txt_discount.getText().isEmpty()) {
                statement.setString(3, null);
                statement.setDouble(4, Double.parseDouble(txt_price.getText()));
            } else {
                statement.setDouble(3, Double.parseDouble(txt_discount.getText()));
                double subPrice = Double.parseDouble(txt_price.getText()) - Double.parseDouble(txt_discount.getText());
                statement.setDouble(4, subPrice);
            }
            statement.executeUpdate();
            showNotification("Service Insert Successful", SUCCESS);
            connect.close();

        } catch (Exception e) {
            showNotification("Service Insert Unsuccessful", WARNING);
        }
        loadData();
        clearData();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            connect = Database.openConnection();
            String sql = "UPDATE service SET name = ?, price = ?, discount = ?, subPrice = ? WHERE serviceID = ?";
            PreparedStatement statement = connect.prepareStatement(sql);
            statement.setString(1, txt_name.getText().toUpperCase());
            statement.setDouble(2, Double.parseDouble(txt_price.getText()));
            if (txt_discount.getText().isEmpty()) {
                statement.setString(3, null);
                statement.setDouble(4, Double.parseDouble(txt_price.getText()));
            } else {
                statement.setDouble(3, Double.parseDouble(txt_discount.getText()));
                double subPrice = Double.parseDouble(txt_price.getText()) - Double.parseDouble(txt_discount.getText());
                statement.setDouble(4, subPrice);
            }
            statement.setInt(5, Integer.parseInt(txt_id.getText()));
            statement.executeUpdate();
            showNotification("Service Update Successful", SUCCESS);
            connect.close();

        } catch (Exception e) {
            showNotification("Service Update Unsuccessful", WARNING);
        }
        loadData();
        clearData();
        disableButton();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", null, JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            try {
                connect = Database.openConnection();
                String sql = "DELETE FROM service WHERE serviceID = " + txt_id.getText();
                PreparedStatement statement = connect.prepareStatement(sql);
                statement.executeUpdate();
                showNotification("Service Delete Successful", SUCCESS);
                connect.close();

            } catch (Exception e) {
                showNotification("Service Delete Successful", WARNING);
            }
            loadData();
            clearData();
            disableButton();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearData();
        disableButton();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        try {
            connect = Database.openConnection();
            String sql = "SELECT * FROM service WHERE ";
            sql = sql + "serviceID LIKE '%" + search.getText() + "%' OR ";
            sql = sql + "name LIKE '%" + search.getText() + "%'";
            PreparedStatement statement = connect.prepareStatement(sql);

            ResultSet result = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbl_service.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String id = result.getString("ServiceID");
                String name = result.getString("name");
                String price = result.getString("price");
                String discount = result.getString("discount");
                String subPrice = result.getString("subPrice");

                model.addRow(new Object[]{id, name, price, discount, subPrice});
            }
            connect.close();

        } catch (Exception e) {
            showNotification("Error", WARNING);
        }
    }//GEN-LAST:event_searchKeyReleased

    private void tbl_serviceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_serviceMouseClicked
        enableButton();
        int row = tbl_service.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_service.getModel();

        txt_id.setText(model.getValueAt(row, 0).toString());
        txt_name.setText(model.getValueAt(row, 1).toString());
        txt_price.setText(model.getValueAt(row, 2).toString());
        txt_discount.setText(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbl_serviceMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_discount;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_userDetails;
    private javax.swing.JTextField search;
    private javax.swing.JTable tbl_service;
    private javax.swing.JTextField txt_discount;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
