package PopUpWindow;

import Class.Database;
import Class.JPanelLoader;
import Panel.customerPanel;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class addVehicleWindow extends javax.swing.JFrame {

    JPanelLoader panalLoad = new JPanelLoader();
    Connection connect;
    
    public addVehicleWindow() {
        initComponents();
        customerPanel customer = new customerPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp_gender = new javax.swing.ButtonGroup();
        addVehiclePanel = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        lbl_customerDetails = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_vType = new javax.swing.JLabel();
        lbl_vName = new javax.swing.JLabel();
        lbl_vModel = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        rdb_male = new javax.swing.JRadioButton();
        rdb_female = new javax.swing.JRadioButton();
        person = new javax.swing.JLabel();
        lbl_vNo = new javax.swing.JLabel();
        txt_vNo = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        txt_make = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        lbl_customerDetails.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_customerDetails.setText("Customer Details");

        lbl_firstName.setText("First Name");

        lbl_lastName.setText("Last Name");

        lbl_gender.setText("Gender");

        lbl_phone.setText("Telephone Number");

        lbl_email.setText("E-Mail");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Vehicle Details");

        lbl_vType.setText("Vehicle type");

        lbl_vName.setText("Vehicle Make");

        lbl_vModel.setText("Vehicle Model");

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Type", "BUS", "CAR", "CAB", "DOUBLE CAB", "SUV", "JEEP", "LORRY", "TIPPER", "MOTORCYCLE", "THREE WHEEL", "HEAVY-DUTY", "TRCTOR", "OTHER" }));
        cmb_type.setToolTipText("");

        btngrp_gender.add(rdb_male);
        rdb_male.setText("Male");
        rdb_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_maleActionPerformed(evt);
            }
        });

        btngrp_gender.add(rdb_female);
        rdb_female.setText("Female");
        rdb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_femaleActionPerformed(evt);
            }
        });

        person.setPreferredSize(new java.awt.Dimension(200, 200));

        lbl_vNo.setText("Vahicle No.");

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_add_30px_1.png"))); // NOI18N
        btn_add.setText("Add");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_cancel_30px_1.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_gender)
                                    .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lastName)
                                    .addComponent(lbl_firstName)
                                    .addComponent(lbl_email))
                                .addGap(18, 18, 18)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainLayout.createSequentialGroup()
                                        .addComponent(rdb_male)
                                        .addGap(24, 24, 24)
                                        .addComponent(rdb_female))
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txt_firstName)))
                            .addComponent(lbl_customerDetails))
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel7))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_vName)
                                    .addComponent(lbl_vType)
                                    .addComponent(lbl_vModel)
                                    .addComponent(lbl_vNo))
                                .addGap(13, 13, 13)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_vNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_make)
                                    .addComponent(txt_model, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addContainerGap(277, Short.MAX_VALUE)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_cancel)
                        .addGap(0, 227, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(lbl_customerDetails)
                                .addGap(10, 10, 10)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_firstName)
                                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lastName))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_gender)
                                    .addComponent(rdb_male)
                                    .addComponent(rdb_female))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_phone)
                                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_email)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vNo)
                                    .addComponent(txt_vNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vName)
                                    .addComponent(txt_make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vModel)
                                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_cancel))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout addVehiclePanelLayout = new javax.swing.GroupLayout(addVehiclePanel);
        addVehiclePanel.setLayout(addVehiclePanelLayout);
        addVehiclePanelLayout.setHorizontalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 983, Short.MAX_VALUE)
            .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addVehiclePanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        addVehiclePanelLayout.setVerticalGroup(
            addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
            .addGroup(addVehiclePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(addVehiclePanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addVehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addVehiclePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rdb_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_maleActionPerformed
        person.setIcon(new ImageIcon("D:\\COT\\COTFinalProject\\src\\Icons\\icons8_person_200px.png"));
        person.setHorizontalAlignment(person.CENTER);
        person.setVerticalAlignment(person.CENTER);
    }//GEN-LAST:event_rdb_maleActionPerformed

    private void rdb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_femaleActionPerformed
        person.setIcon(new ImageIcon("D:\\COT\\COTFinalProject\\src\\Icons\\icons8_person_female_200px.png"));
        person.setHorizontalAlignment(person.CENTER);
        person.setVerticalAlignment(person.CENTER);
    }//GEN-LAST:event_rdb_femaleActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            connect = Database.openConnection();
            String sql = "INSERT INTO vehicle(vehicleNo, type, make, model, firstName, lastName, gender, phone, email) VALUES('";
            sql = sql + txt_vNo.getText().toUpperCase() + "','";
            sql = sql + cmb_type.getSelectedItem() + "','";
            sql = sql + txt_make.getText().toUpperCase() + "','";
            sql = sql + txt_model.getText().toUpperCase() + "','";
            sql = sql + txt_firstName.getText().toUpperCase() + "','";
            sql = sql + txt_lastName.getText().toUpperCase() + "','";

            if (rdb_male.isSelected()) {
                sql = sql + "MALE','";
            } else if (rdb_female.isSelected()) {
                sql = sql + "FEMALE','";
            }

            sql = sql + txt_phone.getText() + "','";
            sql = sql + txt_email.getText() + "')";

            PreparedStatement statement = connect.prepareStatement(sql);
            statement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Insert Successful");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        this.dispose();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addVehicleWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addVehiclePanel;
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancel;
    private javax.swing.ButtonGroup btngrp_gender;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl_customerDetails;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_vModel;
    private javax.swing.JLabel lbl_vName;
    private javax.swing.JLabel lbl_vNo;
    private javax.swing.JLabel lbl_vType;
    private javax.swing.JPanel main;
    private javax.swing.JLabel person;
    private javax.swing.JRadioButton rdb_female;
    private javax.swing.JRadioButton rdb_male;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_make;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_vNo;
    // End of variables declaration//GEN-END:variables
}
