package Panel;

import Class.Database;
import Notification.Notification;
import Notification.Notification.Type;
import TableActionButton.Appointment.appointmentTableActionCellEditor;
import TableActionButton.Appointment.appointmentTableActionCellRender;
import TableActionButton.Waiting.waitingTableActionCellEditor;
import TableActionButton.Waiting.waitingTableActionCellRender;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author CJ
 */
public class appointmentPanel extends javax.swing.JPanel {

    Connection connect;
    private int appointmentIdCheck;
    
    public appointmentPanel() {
        initComponents();
        loadAppointmentList();
        loadWaitingList();
    }

    private void loadAppointmentList() {
        // Load Appointment Table
        try {
            connect = Database.openCloudConnection();
            String sql = "SELECT vehicleNumber, name FROM appointments a ";
            sql = sql + "INNER JOIN services s ON a.service_id = s.id ";
            sql = sql + "WHERE status = 'pending' ORDER BY date";
            PreparedStatement statement = connect.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tbl_appointmentList.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String vNo = result.getString("vehicleNumber");
                String name = result.getString("name");

                model.addRow(new Object[]{vNo, name});
            }

            tbl_appointmentList.getColumnModel().getColumn(2).setCellRenderer(new appointmentTableActionCellRender());
            tbl_appointmentList.getColumnModel().getColumn(2).setCellEditor(new appointmentTableActionCellEditor(this));

            connect.close();

        } catch (Exception e) {
            showNotification("Error", Type.WARNING);
        }
    }

    private void loadWaitingList() {
        try {
            // Load Appointment Table
            connect = Database.openCloudConnection();
            String sql = "SELECT vehicleNumber, name FROM appointments a ";
            sql = sql + "INNER JOIN services s ON a.service_id = s.id ";
            sql = sql + "WHERE status = 'in_progress' ORDER BY date";
            PreparedStatement statement = connect.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tbl_waitingList.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String vNo = result.getString("vehicleNumber");
                String name = result.getString("name");

                model.addRow(new Object[]{vNo, name});
            }
            
            tbl_waitingList.getColumnModel().getColumn(2).setCellRenderer(new waitingTableActionCellRender());
            tbl_waitingList.getColumnModel().getColumn(2).setCellEditor(new waitingTableActionCellEditor(this));
            
            connect.close();

        } catch (Exception e) {
            showNotification("Error", Type.WARNING);
        }
    }
    
    private void showNotification(String message, Notification.Type type) {
        new Notification(this, type, Notification.Location.TOP_CENTER, message).showNotification();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_search = new javax.swing.JLabel();
        srh_appointmentList = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_waitingList = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_appointmentList = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbl_search1 = new javax.swing.JLabel();
        srh_waitingList = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(211, 211, 211));

        lbl_search.setText("Search");

        srh_appointmentList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srh_appointmentListKeyReleased(evt);
            }
        });

        tbl_waitingList.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tbl_waitingList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Number", "Service Name", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_waitingList.setRowHeight(40);
        jScrollPane2.setViewportView(tbl_waitingList);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Appointment List");

        tbl_appointmentList.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N
        tbl_appointmentList.setForeground(new java.awt.Color(51, 51, 51));
        tbl_appointmentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle No", "Service Name", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_appointmentList.setRowHeight(40);
        tbl_appointmentList.setSelectionBackground(new java.awt.Color(255, 255, 255));
        tbl_appointmentList.setSelectionForeground(new java.awt.Color(51, 51, 51));
        jScrollPane3.setViewportView(tbl_appointmentList);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("In Progress List");

        lbl_search1.setText("Search");

        srh_waitingList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                srh_waitingListKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbl_search)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srh_appointmentList)
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(110, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbl_search1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(srh_waitingList, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addGap(30, 30, 30))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(srh_appointmentList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_search1)
                    .addComponent(srh_waitingList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void srh_appointmentListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srh_appointmentListKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srh_appointmentListKeyReleased

    private void srh_waitingListKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_srh_waitingListKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_srh_waitingListKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_search1;
    private javax.swing.JTextField srh_appointmentList;
    private javax.swing.JTextField srh_waitingList;
    private javax.swing.JTable tbl_appointmentList;
    private javax.swing.JTable tbl_waitingList;
    // End of variables declaration//GEN-END:variables
}
