package Panel;

import Class.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Notification.Notification;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class customerPanel extends javax.swing.JPanel {

    Connection connect;
    String check;

    public customerPanel() {
        initComponents();
        loadData();
    }

    private void loadData() {
        try {
            connect = Database.openConnection();
            String sql = "SELECT * FROM vehicle v INNER JOIN customer c ON v.customerID = c.customerID";
            PreparedStatement statement = connect.prepareStatement(sql);

            ResultSet result = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String vNo = result.getString("vehicleNo");
                String vType = result.getString("type");
                String vMake = result.getString("make");
                String vModel = result.getString("model");
                String name = result.getString("firstName") + " " + result.getString("lastName");
                String gender = result.getString("gender");
                String phone = result.getString("phone");
                String email = result.getString("email");

                model.addRow(new Object[]{vNo, vType, vMake, vModel, name, gender, phone, email});
            }
            connect.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearData() {
        txt_vNo.setText("");
        cmb_type.setSelectedItem("Choose Type");
        txt_make.setText("");
        txt_model.setText("");
        txt_firstName.setText("");
        txt_lastName.setText("");
        btngrp_gender.clearSelection();
        txt_phone.setText("");
        txt_email.setText("");
        person.setIcon(null);
    }

    private void enableButton() {
        btn_update.setEnabled(true);
        btn_delete.setEnabled(true);
        btn_add.setEnabled(false);
    }

    private void disableButton() {
        btn_update.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_add.setEnabled(true);
    }

    private void showNotification(String Message) {
        Notification noti = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_CENTER, Message);
        noti.showNotification();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btngrp_gender = new javax.swing.ButtonGroup();
        main = new javax.swing.JPanel();
        lbl_customerDetails = new javax.swing.JLabel();
        lbl_firstName = new javax.swing.JLabel();
        lbl_lastName = new javax.swing.JLabel();
        lbl_gender = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_vType = new javax.swing.JLabel();
        lbl_vName = new javax.swing.JLabel();
        lbl_vModel = new javax.swing.JLabel();
        txt_firstName = new javax.swing.JTextField();
        txt_lastName = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        cmb_type = new javax.swing.JComboBox<>();
        rdb_male = new javax.swing.JRadioButton();
        rdb_female = new javax.swing.JRadioButton();
        person = new javax.swing.JLabel();
        lbl_vNo = new javax.swing.JLabel();
        txt_vNo = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        txt_make = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        btn_clear = new javax.swing.JButton();
        lbl_search = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(211, 211, 211));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));

        lbl_customerDetails.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbl_customerDetails.setText("Customer Details");

        lbl_firstName.setText("First Name");

        lbl_lastName.setText("Last Name");

        lbl_gender.setText("Gender");

        lbl_phone.setText("Telephone Number");

        lbl_email.setText("E-Mail");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Vehicle Details");

        lbl_vType.setText("Vehicle type");

        lbl_vName.setText("Vehicle Make");

        lbl_vModel.setText("Vehicle Model");

        cmb_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Type", "BUS", "CAR", "CAB", "DOUBLE CAB", "SUV", "JEEP", "LORRY", "TIPPER", "MOTORCYCLE", "THREE WHEEL", "HEAVY-DUTY", "TRCTOR", "OTHER" }));
        cmb_type.setToolTipText("");

        btngrp_gender.add(rdb_male);
        rdb_male.setText("Male");
        rdb_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_maleActionPerformed(evt);
            }
        });

        btngrp_gender.add(rdb_female);
        rdb_female.setText("Female");
        rdb_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_femaleActionPerformed(evt);
            }
        });

        person.setPreferredSize(new java.awt.Dimension(200, 200));

        lbl_vNo.setText("Vahicle No.");

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add_30px.png"))); // NOI18N
        btn_add.setText("New");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/update_30px.png"))); // NOI18N
        btn_update.setText("Update");
        btn_update.setEnabled(false);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cancel_30px.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/eraser_30px.png"))); // NOI18N
        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_gender)
                                    .addComponent(lbl_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lastName)
                                    .addComponent(lbl_firstName)
                                    .addComponent(lbl_email))
                                .addGap(18, 18, 18)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(mainLayout.createSequentialGroup()
                                        .addComponent(rdb_male)
                                        .addGap(24, 24, 24)
                                        .addComponent(rdb_female))
                                    .addComponent(txt_email, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txt_firstName)))
                            .addComponent(lbl_customerDetails))
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jLabel7))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_vName)
                                    .addComponent(lbl_vType)
                                    .addComponent(lbl_vModel)
                                    .addComponent(lbl_vNo))
                                .addGap(13, 13, 13)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmb_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_vNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_make)
                                    .addComponent(txt_model, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addContainerGap(259, Short.MAX_VALUE)
                        .addComponent(btn_add)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_clear)
                        .addGap(0, 212, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainLayout.createSequentialGroup()
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(lbl_customerDetails)
                                .addGap(10, 10, 10)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_firstName)
                                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_lastName))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_gender)
                                    .addComponent(rdb_male)
                                    .addComponent(rdb_female))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_phone)
                                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_email)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(mainLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vNo)
                                    .addComponent(txt_vNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vName)
                                    .addComponent(txt_make, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_vModel)
                                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(mainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(person, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_update)
                    .addComponent(btn_clear)
                    .addComponent(btn_delete))
                .addGap(10, 10, 10))
        );

        lbl_search.setText("Search by Vehicle No");

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tbl_customer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle No", "Vehicle Type", "Vehicle Make", "Vehicle Model", "Name", "Gender", "Tel. No", "E-mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_customer.setRowHeight(30);
        tbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_customer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbl_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_search)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_search)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            connect = Database.openConnection();
            String sql1 = "INSERT INTO customer(firstName, lastName, gender, phone, email) VALUES(?, ?, ?, ?, ?)";
            PreparedStatement statement1 = connect.prepareStatement(sql1);
            statement1.setString(1, txt_firstName.getText().toUpperCase());
            statement1.setString(2, txt_lastName.getText().toUpperCase());
            if (rdb_male.isSelected()) {
                statement1.setString(3, "MALE");
            } else if (rdb_female.isSelected()) {
                statement1.setString(3, "FEMALE");
            }
            statement1.setInt(4, Integer.parseInt(txt_phone.getText()));
            statement1.setString(5, txt_email.getText());
            statement1.executeUpdate();
            
            String sql2 = "SELECT customerID FROM customer ORDER BY customerID DESC LIMIT 1";
            PreparedStatement statement2 = connect.prepareStatement(sql2);
            ResultSet result = statement2.executeQuery();
            
            int idCheck = 0;
            if (result.next()) {
                idCheck = result.getInt("customerID");
            }
            
            String sql3 = "INSERT INTO vehicle(vehicleNo, type, make, model, customerID) VALUES(?, ?, ?, ?, ?)";
            PreparedStatement statement3 = connect.prepareStatement(sql3);
            statement3.setString(1, txt_vNo.getText().toUpperCase());
            statement3.setString(2, cmb_type.getSelectedItem().toString());
            statement3.setString(3, txt_make.getText().toUpperCase());
            statement3.setString(4, txt_model.getText().toUpperCase());
            statement3.setInt(5, idCheck);
            statement3.executeUpdate();
            
            showNotification("Data Insert Successful");
            connect.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }

        loadData();
        clearData();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        try {
            connect = Database.openConnection();
            String sql = "UPDATE vehicle SET vehicleNo = ?, type = ?, make = ?, model = ?, firstName = ?, lastName = ?, gender = ?, phone = ?, email = ? WHERE vehicleNo = ?";
            PreparedStatement statement = connect.prepareStatement(sql);
            statement.setString(1, txt_vNo.getText().toUpperCase());
            statement.setString(2, cmb_type.getSelectedItem().toString());
            statement.setString(3, txt_make.getText().toUpperCase());
            statement.setString(4, txt_model.getText().toUpperCase());
            statement.setString(5, txt_firstName.getText().toUpperCase());
            statement.setString(6, txt_lastName.getText().toUpperCase());
            if (rdb_male.isSelected()) {
                statement.setString(7, "MALE");
            } else if (rdb_female.isSelected()) {
                statement.setString(7, "FEMALE");
            }
            statement.setInt(8, Integer.parseInt(txt_phone.getText()));
            statement.setString(9, txt_email.getText());
            statement.setString(10, check);
            statement.executeUpdate();
            showNotification("Data Update Successful");
            connect.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        loadData();
        clearData();
        disableButton();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete?", null, JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION) {
            try {
                connect = Database.openConnection();
                String sql = "DELETE FROM vehicle WHERE vehicleNo = '" + txt_vNo.getText() + "'";
                PreparedStatement statement = connect.prepareStatement(sql);
                statement.executeUpdate();
                showNotification("Data Delete Successful");
                connect.close();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
            }

            loadData();
            clearData();
            disableButton();
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        clearData();
    }//GEN-LAST:event_btn_clearActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try {
            connect = Database.openConnection();
            String sql = "SELECT * FROM vehicle WHERE ";
            sql = sql + "firstName LIKE '%" + txt_search.getText() + "%' OR ";
            sql = sql + "lastName LIKE '%" + txt_search.getText() + "%' OR ";
            sql = sql + "vehicleNo LIKE '%" + txt_search.getText() + "%'";
            PreparedStatement statement = connect.prepareStatement(sql);

            ResultSet result = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
            model.setRowCount(0);

            while (result.next()) {
                String vNo = result.getString("vehicleNo");
                String vType = result.getString("type");
                String vMake = result.getString("make");
                String vModel = result.getString("model");
                String name = result.getString("firstName") + " " + result.getString("lastName");
                String gender = result.getString("gender");
                String phone = result.getString("phone");
                String email = result.getString("email");

                model.addRow(new Object[]{vNo, vType, vMake, vModel, name, gender, phone, email});
            }
            connect.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void tbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerMouseClicked
        int row = tbl_customer.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();

        txt_vNo.setText(model.getValueAt(row, 0).toString());
        cmb_type.setSelectedItem(model.getValueAt(row, 1).toString());
        txt_make.setText(model.getValueAt(row, 2).toString());
        txt_model.setText(model.getValueAt(row, 3).toString());

        String name = model.getValueAt(row, 4).toString();
        String[] nameParts = name.split(" ");

        if (nameParts.length >= 2) {
            txt_firstName.setText(nameParts[0]);
            txt_lastName.setText(nameParts[1]);
        } else {
            txt_firstName.setText(nameParts[0]);
            txt_lastName.setText("");
        }

        String gender = model.getValueAt(row, 5).toString();
        if ("MALE".equals(gender)) {
            rdb_male.setSelected(true);
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("Icons/male_200px.png"));
            person.setIcon(icon);
        } else if ("FEMALE".equals(gender)) {
            rdb_female.setSelected(true);
            ImageIcon icon = new ImageIcon(getClass().getClassLoader().getResource("Icons/female_200px.png"));
            person.setIcon(icon);
        }

        txt_phone.setText(model.getValueAt(row, 6).toString());
        txt_email.setText(model.getValueAt(row, 7).toString());
        check = txt_vNo.getText();
        enableButton();
    }//GEN-LAST:event_tbl_customerMouseClicked

    private void rdb_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_maleActionPerformed
        person.setIcon(new ImageIcon("D:\\COT\\COTFinalProject\\Service-Management-System\\Desktop\\src\\Icons\\male_200px.png"));
        person.setHorizontalAlignment(person.CENTER);
        person.setVerticalAlignment(person.CENTER);
    }//GEN-LAST:event_rdb_maleActionPerformed

    private void rdb_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_femaleActionPerformed
        person.setIcon(new ImageIcon("D:\\COT\\COTFinalProject\\Service-Management-System\\Desktop\\src\\Icons\\female_200px.png"));
        person.setHorizontalAlignment(person.CENTER);
        person.setVerticalAlignment(person.CENTER);
    }//GEN-LAST:event_rdb_femaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup btngrp_gender;
    private javax.swing.JComboBox<String> cmb_type;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_customerDetails;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_firstName;
    private javax.swing.JLabel lbl_gender;
    private javax.swing.JLabel lbl_lastName;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_vModel;
    private javax.swing.JLabel lbl_vName;
    private javax.swing.JLabel lbl_vNo;
    private javax.swing.JLabel lbl_vType;
    private javax.swing.JPanel main;
    private javax.swing.JLabel person;
    private javax.swing.JRadioButton rdb_female;
    private javax.swing.JRadioButton rdb_male;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_make;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_vNo;
    // End of variables declaration//GEN-END:variables
}
