package Panel;

import Class.Database;
import Class.JPanelLoader;
import UI.LoginUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Notification.Notification;
import javax.swing.JOptionPane;

public class forgotPasswordPanel extends javax.swing.JPanel {

    Connection connect;
    JPanelLoader panelLoad = new JPanelLoader();
    LoginUI login;

    public forgotPasswordPanel(LoginUI login) {
        initComponents();
        lbl_checkUsername.setVisible(false);
        this.login = login;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_password = new javax.swing.JLabel();
        txt_newPassword = new javax.swing.JPasswordField();
        btn_ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbl_password1 = new javax.swing.JLabel();
        txt_confirmPassword = new javax.swing.JPasswordField();
        btn_cancel = new javax.swing.JButton();
        lbl_checkUsername = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lbl_username.setText("Username");

        lbl_password.setText("New Password");

        btn_ok.setText("OK");
        btn_ok.setPreferredSize(new java.awt.Dimension(70, 27));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 1, 25)); // NOI18N
        jLabel1.setText("Forgot Password");

        lbl_password1.setText("Confirm Password");

        btn_cancel.setText("Cancel");
        btn_cancel.setPreferredSize(new java.awt.Dimension(70, 27));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        lbl_checkUsername.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lbl_checkUsername.setForeground(new java.awt.Color(255, 0, 0));
        lbl_checkUsername.setText("Username Incorrect");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_checkUsername)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_username)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_confirmPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_password1)
                                .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_password))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lbl_username))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_checkUsername)))
                .addGap(20, 20, 20)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_password1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        connect = Database.openConnection();
        try {
            String sql1 = "SELECT username FROM user";
            PreparedStatement statement1 = connect.prepareStatement(sql1);
            ResultSet result1 = statement1.executeQuery();

            while (result1.next()) {
                if (result1.getString("username").equals(txt_username.getText())) {
                    lbl_checkUsername.setVisible(false);
                    break;
                } else {
                    lbl_checkUsername.setVisible(true);
                }
            }

            if (!txt_newPassword.getText().isEmpty() && !txt_confirmPassword.getText().isEmpty()) {
                if (txt_confirmPassword.getText().equals(txt_newPassword.getText())) {
                    String sql2 = "UPDATE user SET password = ? WHERE username = ?";
                    PreparedStatement statement2 = connect.prepareStatement(sql2);
                    statement2.setString(1, txt_newPassword.getText());
                    statement2.setString(2, txt_username.getText());
                    statement2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Password Change Successful");

                    loginPanel login = new loginPanel(this.login);
                    panelLoad.jPanelLoader(this, login);
                }

            } else {
                Notification notification = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_CENTER, "Empty Field");
                notification.showNotification();
            }
            connect.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        loginPanel login = new loginPanel(this.login);
        panelLoad.jPanelLoader(this, login);
    }//GEN-LAST:event_btn_cancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_checkUsername;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_password1;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField txt_confirmPassword;
    private javax.swing.JPasswordField txt_newPassword;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
