package TableActionButton.Appointment;

import Class.Database;
import Class.JPanelLoader;
import Notification.Notification;
import Notification.Notification.Type;
import Panel.appointmentPanel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chala
 */
public class appointmentPanelAction extends javax.swing.JPanel {

    JPanelLoader panelLoad = new JPanelLoader();
    private JTable table;
    private JPanel panel;
    Connection connect;
    private int appointmentIdCheck;

    public appointmentPanelAction(JTable table, JPanel panel) {
        initComponents();
        this.table = table;
        this.panel = panel;
    }

    private void getAppointmentId(String vNo, String name) {
        try {
            connect = Database.openCloudConnection();
            String sql = "SELECT a.id FROM appointments a INNER JOIN services s ON a.service_id = s.id ";
            sql = sql + "WHERE a.vehicleNumber = '" + vNo + "' AND ";
            sql = sql + "s.name = '" + name + "'";
            PreparedStatement statement = connect.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            if (result.next()) {
                appointmentIdCheck = result.getInt("id");
            }

        } catch (Exception e) {
            showNotification("Error", Type.WARNING);
        }
    }

    private void showNotification(String message, Notification.Type type) {
        new Notification(this, type, Notification.Location.TOP_CENTER, message).showNotification();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButton1 = new TableActionButton.Appointment.appointmentActionButton();

        actionButton1.setForeground(new java.awt.Color(255, 255, 255));
        actionButton1.setText("Start");
        actionButton1.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        actionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButton1ActionPerformed
        int row = table.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        String vNo = model.getValueAt(row, 0).toString();
        String name = model.getValueAt(row, 1).toString();
        getAppointmentId(vNo, name);

        try {
            connect = Database.openCloudConnection();
            String sql = "UPDATE appointments SET status = 'in_progress' WHERE id = " + appointmentIdCheck;
            PreparedStatement statement = connect.prepareStatement(sql);
            statement.executeUpdate();

            appointmentPanel appointment = new appointmentPanel();
            panelLoad.jPanelLoader(panel, appointment);

            connect.close();

        } catch (Exception e) {
            showNotification("Error", Type.WARNING);
        }
    }//GEN-LAST:event_actionButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private TableActionButton.Appointment.appointmentActionButton actionButton1;
    // End of variables declaration//GEN-END:variables

}
